### ISSUE TITLE
[BUG] Configuration File Don't Work

### ISSUE THREAD

**Issue by michelangeloesprimo-star** [aandrew-me/ytDownloader#366]
**Bug Description**

**To Reproduce**
1. 

**Screenshots**

**Info (please complete the following information):**
 - Operating system:
 - App version:
 - Package version (flatpak/snap/other):

**Comment by michelangeloesprimo-star** [comment]
Configuration File Don't work
Liux Mint 22,2, YT downloader 3.20.2, Appimage & Flatpak version.

**Comment by michelangeloesprimo-star** [comment]
Instructions: --write-thumbnail
--embed-thumbnail
--embed-metadata
--merge-output-format mkv

**Comment by aandrew-me** [comment]
Thanks for reporting. It should be fixed in next update. You can paste those options here for now, it will work:

<img width="1766" height="334" alt="Image" src="https://github.com/user-attachments/assets/9a468a5d-fe39-49a2-87ee-1f1c13219382" />
And I think its a more user friendly way

**Comment by Qloulia** [comment]
I'm on the latest version but it seems still not working, I've pasted my command lines in there and the downloads are not using the configuration at all

**Comment by aandrew-me** [comment]
As I said, config file will not work, set the options in Preferences

**Comment by Qloulia** [comment]
🥲I did, i didn't use file, I wrote the lines in the box

**Comment by aandrew-me** [comment]
Okay, what lines did you write

**Comment by Qloulia** [comment]
like these:
--cookies /Users/.../Movies/yt-dlp/cookies/....txt 
-f "bestvideo+bestaudio/best"
--embed-metadata
--merge-output-format mp4
--sleep-interval 5
--playlist-start 1
--playlist-end 5
-o "/Users/.../Movies/yt-dlp/%(playlist_title)s/%(playlist_index)03d_%(title)s.%(ext)s"

**Comment by aandrew-me** [comment]
Why does your file path start with /Users?
And are you getting any error messages?

**Comment by Qloulia** [comment]
I don't really understand these rules but they works fine in terminal, and yes when I'm downloading playlist I'm getting errors like 
ERROR: [youtubel iTfS2_ZkTgE: Sign in to confirm you're not a bot. Use --cookies-from-browser or -cookies for the
authentication.
I found one closed issue saying only firefox cookie is working so I changed it to firefox in preference and the download starts but my other lines like renaming and playlist number didn't work so I don't think my command lines are working as it should

**Comment by aandrew-me** [comment]
The command line args are only for downloading single videos, not playlists. For customizing playlist name, there is a separate setting in Preferences

**Comment by Qloulia** [comment]
oh now it's very clear to me! As long as my lines don't involve playlist setting , and using firefox cookie, it should be working right ?

**Comment by aandrew-me** [comment]
Yes, they are not used when downloading playlists

**Comment by Qloulia** [comment]
not even only embedding meta?

**Comment by Qloulia** [comment]
oh wait I'm trying to download an unfinished  playlist and getting erros below, there errors also happened the first time I used ytdownload

Error code: 1 Stderr: WARNING: [youtubel No supported JavaScript runtime found. Only deno is enabled by default; to use another runtime add --
RUNTIME I• PATHI
to your command/config. YouTube extraction without a
runtime has been deprecated, and some formats may be missing. See
https://github.com/yt-dlp/yt-dlp/wiki/EJS for details on installing
one WARNING:
[youtubel
No title found in player responses; falling back to title from initial
data. Other metadata may also be missing ERROR: [youtubel iTfS2_ZkTgE: Sign in to confirm you're not a bot. Use --cookies-from-browser or
-cookies for the
authentication.

**Comment by Qloulia** [comment]
never mind, it's probably my setting and network problem, thank you very much!!!

**Comment by ibigfire** [comment]
> The command line args are only for downloading single videos, not playlists. For customizing playlist name, there is a separate setting in Preferences

So how does one apply custom yt-dlp options that are unrelated to names to playlist downloads, if possible?  When wanting to use custom options, having to download videos one by one takes a very long time for lengthy playlists.

**Comment by LooOOooM** [comment]
Hi I am using FC43 YtDownloader in its Version 3.20.2 Flatpak version. I configured with faltseal that yTdownloader is allowed to write in my home and in the path of dest. Everything is working fine.

However it is very annoing to me that i always have to change the given titel "Juche - Rise [gp_sXVk2zbM]" has it has crappy stuff within to "Juche - Rise". However I thought there be a way to change the default behalvier. There for I added  first in preferences  unter the input of yt-dlp options "--extract-audio --audio-format mp3 --audio-quality 0 --output %(title)s.%(ext)s --restrict-filenames" and restarted teo program. However it seems to get ignored.

then I activated the checkbox using YtDownloader config and add (overwrite) to my already existing ~/.ytDownloader/config the following:

```

-x

--audio-format mp3

--audio-quality 0

--no-mtime

-o '~/where/ever/I/like/my/data/to/be/%(uploader)s - %(title)s.%(ext)s'

--restrict-filenames
```

However also this gets ignored. Yes I restarted the program meanwhile.


When I go into ~/.ytDownloader and execute i.e:

`./ytdlp --extract-audio --audio-format mp3 --audio-quality 0 --output '%(title)s.%(ext)s' --restrict-filenames 'https://www.youtube.com/watch?v=gp_sXVk2zbM'`
then all works as it is supposted to 


So,-
Why is config my ignored.




Even more strange... If i disabled the checkbox "use Config"  move the config  (mv config confg.bak) out of the way just to be sure ;) and remove all given options in the input field to be default, restart the program and try to add a link I get the following error :


<img width="2001" height="755" alt="Image" src="https://github.com/user-attachments/assets/44fa6b0b-9575-4a57-a79f-098cea807310" />

**Comment by aandrew-me** [comment]
The config file is ignored currently, it will be fixed in next version, you can paste everything from the config file into the textbox below 'Setze elgene yt-dlp Optionen'

**Comment by LooOOooM** [comment]
Ok, after hustleling around further. I managed it - Year Textbox -- But I saied this was not working neither .

For some leason the textbox wants my --output option in the end. Then it downloads as it should, HOWEVER
in the title filed still the wrong name is displayed.

**Comment by aandrew-me** [comment]
Well the title field will show the 'wrong name' because its not possible to display the title based on your config options. However the output file will follow the config options
